---
abstract: 'Bus drivers, Instrument drivers, and measurement scripts'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
  - 'Andreas K. Huettel <mail@akhuettel.de>'
  - 'Daniela Taubert <daniela.taubert@physik.uni-muenchen.de>'
  - 'Florian Olbrich <florian.olbrich@physik.uni-r.de>'
configure_requires:
  Module::Build: 0.36
conflicts:
  Lab::Instrument: '< 2.91'
  Lab::Tools: '< 2.91'
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Measurement
provides:
  Lab::Bus:
    file: lib/Lab/Bus.pm
    version: 2.91
  Lab::Bus::DEBUG:
    file: lib/Lab/Bus/DEBUG.pm
    version: 2.91
  Lab::Bus::DEBUG::HumanInstrument:
    file: lib/Lab/Bus/DEBUG.pm
    version: 2.91
  Lab::Bus::LinuxGPIB:
    file: lib/Lab/Bus/LinuxGPIB.pm
    version: 2.91
  Lab::Bus::MODBUS_RS232:
    file: lib/Lab/Bus/MODBUS_RS232.pm
    version: 2.91
  Lab::Bus::RS232:
    file: lib/Lab/Bus/RS232.pm
    version: 2.91
  Lab::Bus::VISA:
    file: lib/Lab/Bus/VISA.pm
    version: 2.91
  Lab::Connection:
    file: lib/Lab/Connection.pm
    version: 2.91
  Lab::Connection::DEBUG:
    file: lib/Lab/Connection/DEBUG.pm
    version: 2.91
  Lab::Connection::GPIB:
    file: lib/Lab/Connection/GPIB.pm
    version: 2.91
  Lab::Connection::LinuxGPIB:
    file: lib/Lab/Connection/LinuxGPIB.pm
    version: 2.91
  Lab::Connection::MODBUS_RS232:
    file: lib/Lab/Connection/MODBUS_RS232.pm
    version: 2.91
  Lab::Connection::VISA:
    file: lib/Lab/Connection/VISA.pm
    version: 2.91
  Lab::Connection::VISA_GPIB:
    file: lib/Lab/Connection/VISA_GPIB.pm
    version: 2.91
  Lab::Data::Meta:
    file: lib/Lab/Data/Meta.pm
    version: 2.91
  Lab::Data::PDL:
    file: lib/Lab/Data/PDL.pm
    version: 2.91
  Lab::Data::Plotter:
    file: lib/Lab/Data/Plotter.pm
    version: 2.91
  Lab::Data::Writer:
    file: lib/Lab/Data/Writer.pm
    version: 2.91
  Lab::Data::XMLtree:
    file: lib/Lab/Data/XMLtree.pm
    version: 2.91
  Lab::Exception:
    file: lib/Lab/Exception.pm
    version: 2.91
  Lab::Exception::Base:
    file: lib/Lab/Exception.pm
    version: 2.91
  Lab::Instrument:
    file: lib/Lab/Instrument.pm
    version: 2.91
  Lab::Instrument::HP34401A:
    file: lib/Lab/Instrument/HP34401A.pm
    version: 2.91
  Lab::Instrument::HP3458A:
    file: lib/Lab/Instrument/HP3458A.pm
    version: 2.91
  Lab::Instrument::HP83732A:
    file: lib/Lab/Instrument/HP83732A.pm
    version: 2.91
  Lab::Instrument::IPS12010:
    file: lib/Lab/Instrument/IPS12010.pm
    version: 2.91
  Lab::Instrument::MagnetSupply:
    file: lib/Lab/Instrument/MagnetSupply.pm
    version: 2.91
  Lab::Instrument::Multimeter:
    file: lib/Lab/Instrument/Multimeter.pm
    version: 2.91
  Lab::Instrument::SR830:
    file: lib/Lab/Instrument/SR830.pm
    version: 2.91
  Lab::Instrument::Source:
    file: lib/Lab/Instrument/Source.pm
    version: 2.91
  Lab::Instrument::TemperatureControl::TLK43:
    file: lib/Lab/Instrument/TemperatureControl/TLK43.pm
    version: 2.91
  Lab::Instrument::Yokogawa7651:
    file: lib/Lab/Instrument/Yokogawa7651.pm
    version: 2.91
  Lab::Instrument::YokogawaGS200:
    file: lib/Lab/Instrument/YokogawaGS200.pm
    version: 2.91
  Lab::Measurement:
    file: lib/Lab/Measurement.pm
    version: 2.91
  Lab::Measurement::Ladediagramm:
    file: lib/Lab/Measurement/Ladediagramm.pm
    version: 2.91
requires:
  Cwd: 0
  Data::Dumper: 0
  Encode: 0
  Exception::Class: 1.0
  File::Basename: 0
  File::Copy: 0
  Switch: 0
  Term::ReadKey: 0
  Time::HiRes: 0
  XML::DOM: 0
  XML::Generator: 0
  XML::Twig: 0
  encoding::warnings: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Measurement
  homepage: http://www.labmeasurement.de/
  license: http://dev.perl.org/licenses/
version: 2.91
