=pod

=encoding utf-8

=head1 NAME

Lab::Measurement::Installation - Installation guide for Lab::Measurement

=head1 Introduction

Since Lab::Measurement does not contain any device driver code itself, its installation is 
pretty straightforward. However, before you can actually use it, you will have to install
a driver binding back-end, such as Lab::VISA or Linux-GPIB, plus its dependencies. Please 
see the documentation of these packages for more details.

=head1 Installation on Windows

=over

=item * Install a B<32-bit version>  of Strawberry Perl: L<http://strawberryperl.com/download/5.20.3.3/strawberry-perl-5.20.3.3-32bit.msi>. Note
that version 5.22 is not supported (see the comments below). 

=item * Install gnuplot (not mandatory)

=over

=item * Download from L<http://sourceforge.net/project/showfiles.php?group_id=2055> (gp425win32.zip)

=item * Extract and put it somewhere

=item * Add directory containing C<pgnuplot.exe> to path:
My Computer => Properties => Advanced => Environment Variables

=back

=item * Install NI-VISA and the NI IEEE-488.2 driver.

=item * Download Lab::Measurement from
L<https://github.com/lab-measurement/lab-measurement/archive/master.zip> and
extract. 

Build and install with

 cpanm .\lab-measurement-master\VISA
 cpanm .\lab-measurement-master\Measurement

Have fun!

=back

=head2 Notes

On 64-bit windows one needs a 32-bit version of perl with GNU binutils version
<= 2.24. Otherwise linking with the NI-VISA library will fail. The reason for this
are the following bugs in the GNU binutils:

=over

=item * L<https://sourceware.org/bugzilla/show_bug.cgi?id=17910>

=item * L<https://sourceware.org/bugzilla/show_bug.cgi?id=16598>

=back

These are fixed in the most recent version of the binutils. Once this version
(2.26) is included in Strawberry Perl, it should be possible to use a 64-bit
version of perl.

It is not possible to use Strawberry Perl 5.22 as this version uses binutils
2.25. 




=head1 Installation on Linux

As a Linux user you will probably be able to figure out most things yourself. 

=over

=item

Install the dependencies

Best you'll use your distribution package management. You need

 XML::Generator
 XML::DOM
 XML::Twig
 YAML
 ... and GnuPlot

=item

Install Lab::Measurement

=over

=item *

Unzip/copy sources

=item *

Run the following commands in the source directory

    perl Build.PL
    perl Build
    perl Build install

=back

=item

Have fun!

=back

=head1 COPYRIGHT AND LICENCE

 (c) 2010, 2011 Daniel Schröer, Andreas K. Hüttel, Daniela Taubert, and others.
     2012       Andreas K. Hüttel

=cut

