=pod

=encoding utf-8

=head1 NAME

Lab::Measurement::Installation - Installation guide for Lab::Measurement

=head1 Introduction

Since Lab::Measurement does not contain any device driver code itself, its installation is 
pretty straightforward. However, before you can actually use it, you will have to install
a driver binding back-end, such as Lab::VISA or Linux-GPIB, plus its dependencies. Please 
see the documentation of these packages for more details.

=head1 Installation on Windows

=over

=item * Install L<Strawberry Perl|http://strawberryperl.com/download/5.20.3.3/strawberry-perl-5.20.3.3-32bit.msi>. If you want to use NI-VISA, see the comments on supported perl versions in L<Lab::VISA's installation guide|http://labmeasurement.de/docs/VISA-Installation.html>

=item * Install gnuplot (not mandatory)

=over

=item * L<Download|http://sourceforge.net/project/showfiles.php?group_id=2055>, extract and put it somewhere

=item * Add directory containing C<pgnuplot.exe> to path:
My Computer => Properties => Advanced => Environment Variables

=back

=item * Build and install:

 cpanm Lab::Measurement

=item * If you need the NI-VISA backend for your instruments follow L<Lab::VISA's installation guide|http://labmeasurement.de/docs/VISA-Installation.html>

=item * Have fun!

=back

=head1 Installation on Linux

As a Linux user you will probably be able to figure out most things yourself. 

=over

=item

Install the dependencies

Best you'll use your distribution package management. You need

 XML::Generator
 XML::DOM
 XML::Twig
 YAML
 ... and GnuPlot

=item

Install Lab::Measurement

=over

=item *

Unzip/copy sources

=item *

Run the following commands in the source directory

    perl Build.PL
    perl Build
    perl Build install

=back

=item

Have fun!

=back

=head1 COPYRIGHT AND LICENCE

 (c) 2010, 2011 Daniel Schröer, Andreas K. Hüttel, Daniela Taubert, and others.
     2012       Andreas K. Hüttel

=cut

