=head1 NAME

VISA - Perl interface to National Instrument's NI-VISA library

=head1 SYNOPSIS

    use VISA;

=head1 DESCRIPTION

=head1 ABSTRACT

blablabla

=head1 FUNCTIONS

=head2 viOpenDefaultRM()

=head2 viOpen($resource_manager, $resource_name, $access_mode, timeout)

=head2 viClear($object);

=head2 viSetAttribute($object, $attr_name, $attr_value);

=head2 viGetAttribute($object, $attr_name)

=head2 viRead($instrument, $max_read)

=head2 viWrite($instrument, $string, $length)

=head2 viClose($object)

=head1 CAVEATS/BUGS

probably many

=head1 SEE ALSO

=over 4

=item VISA::Instrument

=back

=head1 AUTHOR

This is $Id$

=head1 COPYRIGHT

Don't know. This swig-based interface is copyright 2004 Daniel Schröer (L<http://www.danielschroeer.de>).
It is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

For the rest National Instruments or the VXI Consortium will probably have a word to say.

=cut

