=head1 NAME

VISA - Perl interface to National Instrument's NI-VISA library

=head1 SYNOPSIS

    use VISA;

=head1 DESCRIPTION

dfsdfdsddfsfdfsa

=head1 ABSTRACT

blablabla

=head1 FUNCTIONS

=head2 viOpenDefaultRM

    ($status, $resource_manager)=
        VISA::viOpenDefaultRM();

Opens the default resource manager.

=head2 viFindRsrc

    ($status, $listhandle, $count, $first_resource_name)=
        VISA::viFindRsrc($resource_manager, $regular_expression);

=head2 viOpen

    ($status, $instrument)=
        VISA::viOpen($resource_manager, $resource_name, $access_mode, $timeout);

Opens an instrument.

=head2 viClear

    $status=VISA::viClear($object);

=head2 viSetAttribute

    $status=VISA::viSetAttribute($object, $attr_name, $attr_value);

=head2 viGetAttribute

    ($status, $attribute)=
	    viGetAttribute($object, $attr_name);

=head2 viRead

    ($status, $result, $read_count)=
	    VISA::viRead($instrument, $max_read);

=head2 viWrite

    ($status, $write_count)=
	    VISA::viWrite($instrument, $string, $length);

=head2 viClose

    $status=viClose($object);

=head1 CAVEATS/BUGS

probably many

=head1 SEE ALSO

=over 4

=item VISA::Instrument

=back

=head1 AUTHOR

This is $Id$

=head1 COPYRIGHT

Don't know. This swig-based interface is copyright 2004 Daniel Schröer (L<http://www.danielschroeer.de>).
It is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

For the rest National Instruments or the VXI Consortium will probably have a word to say.

=cut

