#DistZilla: +PodWeaver
#PODNAME: Lab::Measurement::Roadmap
#ABSTRACT: Some notes and speculations on future L::M development

=pod

=head1 3.700: feature completeness Moose vs. old code

=over

=item *

Old instrument or xpress code prints an informative message about the new Moose
framework.

=item *

Remaining features that are still missing in the Moose code are ported from old
drivers or implemented.

=item *

Missing hardware support: SignalRecovery7265, HP34420A(?), Keithley2000, SR830 aux
in/out, HP33120A, HP83732A, MG369xB, U2000, TDS2024B, WR640, TRMC2, TCD(?),
Lakeshore33x, TLK43(?), OI_ILM210, PD11042

=item *

Sweep support: Motor, Phase (for lock-in or signal generator?)


=head1 3.800: legacy code deprecation

Old instrument or xpress code prints a deprecation warning.

=head1 3.900: legacy code removal

The old code is completely removed. Old scripts stop working.

=head1 3.990: move Lab::Moose and friends to Lab::Measurement

Lab::Moose -> Lab::Measurement, Lab::Moose::Instrument -> Lab::Instrument,
...

More directory cleanup is possible, e.g. introducing a Lab::Role:: subdir...

=head1 4.000: party!

