#DistZilla: +PodWeaver
#PODNAME: Lab::Measurement::Roadmap
#ABSTRACT: Some notes and speculations on future L::M development

=pod

=head1 3.800: legacy code deprecation

Old instrument or xpress code prints a deprecation warning. (done, 2022-03)

=head1 3.900: legacy code removal

The old code is completely removed. Old scripts stop working. (done, 2022-10)

=head1 3.920: legacy code blocker

A temporary Lab::Measurement module is installed to inform people of the need to
install Lab::Measurement::Legacy for old scripts, for users of CPAN and 
similar managers that do not remove old module versions.

=head1 3.990: copy Lab::Moose to Lab::Measurement

Replace the temporary Lab::Measurement module with an alias for Lab::Moose
(or vice versa).

=head1 4.000: party!

