package Documentation::Web;

use strict;
use base 'Documentation::LabVISAdoc';
use File::Basename;
use Syntax::Highlight::Engine::Simple::Perl;

# todo: need some navigation area common to all pages (autogenerated or not), like a left side menu
#       similar to my homepage (warning: bad html) or grouppage (still offline) or the no-frame LSK version
#
# not sure if we want to keep separate perl modules for offline and online html but it's easier to start this
# way, and if we do a php version we need to do it   

sub new {
    my $self = shift->SUPER::new(@_);
    $self->{list_open} = 0;
    $self->{highlighter} = Syntax::Highlight::Engine::Simple::Perl->new();
    return $self;
}

sub start {
    my ($self, $title, $authors) = @_;
    open $self->{index_fh}, ">", "$$self{docdir}/toc.php" or die $!;
    
    print {$self->{index_fh}} $self->_get_header($title);
 	print {$self->{index_fh}} qq{
 	    <h1><a href="../index.html">Lab::VISA</a> Documentation</h1>
 	    <p>$authors</p>
 	};
}

sub start_section {
    my ($self, $level, $title) = @_;
    if ($self->{list_open}) {
        print {$self->{index_fh}} "</ul>\n";
        $self->{list_open} = 0;
    }
    print {$self->{index_fh}} "<h$level>$title</h$level>\n";
}

sub process_element {
    my ($self, $podfile, $params, @sections) = @_;
    my $basename = fileparse($podfile,qr{\.(pod|pm)});
    my $hascode = ($podfile =~ /\.(pl|pm)$/);
    
    # pod page
    my $parser = MyPodXHTML->new();
    my $title = "$sections[0]: $basename";
    my $html;
    $parser->output_string(\$html);
    $parser->parse_file($podfile);
    open OUTFILE, ">", "$$self{docdir}/$basename.php" or die;
        print OUTFILE $self->_get_header($title);
        print OUTFILE qq(<h1><a href="toc.php">$sections[0]</a>: <span class="basename">$basename</span></h1>\n);
        print OUTFILE $hascode ? qq{<p>(<a href="$basename\_source.php">Source code</a>)</p>} : "";
        print OUTFILE $html;
        print OUTFILE $self->_get_footer();
    close OUTFILE;
    
    # highlighted source file
    if ($hascode) {
        my $source = $self->{highlighter}->doFile(
            file      => $podfile,
            tab_width => 4,
            encode    => 'iso-8859-1'
        );
        my $title = "$sections[0]: $basename";
        open SRCFILE, ">", "$$self{docdir}/$basename\_source.php" or die;
            print SRCFILE $self->_get_header($title);
            print SRCFILE qq(<h1><a href="toc.php">$sections[0]</a>: <span class="basename">$basename</span></h1>\n);
            print SRCFILE qq{<p>(<a href="$basename.php">Documentation</a>)</p>};
            print SRCFILE "<pre>$source</pre>\n";
            print SRCFILE $self->_get_footer();
        close SRCFILE;
    }
    
    # link in toc page
    unless ($self->{list_open}) {
        print {$self->{index_fh}} "<ul>\n";
        $self->{list_open} = 1;
    }
    print {$self->{index_fh}} qq(<li><a class="index" href="$basename.php">$basename</a></li>\n);
}

sub finish {
    my $self = shift;
    if ($self->{list_open}) {
        print {$self->{index_fh}} "</ul>\n";
        $self->{list_open} = 0;
    }
 	print {$self->{index_fh}} q{<p><a href="documentation.pdf">This documentation as PDF</a></p>};
    print {$self->{index_fh}} $self->_get_footer();
    close $self->{index_fh};
}

sub _get_header {
    my ($self, $title) = @_;
    return <<HEADER;
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
   		<link rel="stylesheet" type="text/css" href="../doku.css"/>
   		<title>$title</title>
 	</head>
 	<body>
HEADER
}

sub _get_footer {
    return <<FOOTER;

<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=5798171; 
var sc_invisible=1; 
var sc_security="385de927"; 
</script>

<script type="text/javascript"
    src="http://www.statcounter.com/counter/counter.js"></script>
<noscript>
<div class="statcounter"><a title="free hit counter"
    href="http://www.statcounter.com/" target="_blank"><img
    class="statcounter"
    src="http://c.statcounter.com/5798171/0/385de927/1/"
    alt="free hit counter"></a></div>
</noscript>
<!-- End of StatCounter Code -->

 	</body>
</html>
FOOTER
}


package MyPodXHTML;
use strict;
use base 'Pod::Simple::XHTML';
use HTML::Entities;

sub new {
    my $self = shift->SUPER::new();
    $self->html_header('');
    $self->html_footer('');
    $self->html_h_level(2);
    return $self;
}

sub resolve_pod_page_link {
    my ($self, $to, $section) = @_;
    return undef unless defined $to || defined $section;
    if ($to =~ /^Lab/) {
        return (split '::', $to)[-1].".php";
    }
    if (defined $section) {
        $section = '#' . $self->idify($section, 1);
        return $section unless defined $to;
    } else {
        $section = ''
    }

    return ($self->perldoc_url_prefix || '')
        . encode_entities($to) . $section
        . ($self->perldoc_url_postfix || '');
}

1;
